### PR TITLE
Added Tags options to the exporter

### PR DESCRIPTION
**Pull request by h7kanna**
Hi, 
Added tags at the exporter level to add  default tags.

Thanks,

### CODE REVIEW

**Comment by songy23** [comment]
Please sign the CLA.

**Comment by h7kanna** [comment]
I signed it!

**Comment by songy23** [comment]
Please fix the test failures (https://travis-ci.org/census-ecosystem/opencensus-go-exporter-graphite/builds/510168377#L669):
```bash
=== RUN   TestDistributionData
--- FAIL: TestDistributionData (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x600a00]
```

**Comment by h7kanna** [comment]
Yes checking

**Comment by h7kanna** [comment]
Hi, Fixed failing tests. 
Can you please verify and merge this?
Thanks.

**Pull request merged**
